// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zljrsdjgefcgovoztvup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsanJzZGpnZWZjZ292b3p0dnVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODIwNzAsImV4cCI6MjA2NTg1ODA3MH0.JRaGvcwdu1BSTrs5EuUUtdii_JV5kavuWQKg2Xfbt10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);